#!/usr/bin/env python3

"""
Copyright 2017 Pirate Hour Productions

Author: Alan Drees

Purpose: Application class implementation for the system-backup command

"""

import sys
import argparse
import yaml
import subprocess

class SystemBackup:

    def __init__(self, args):
        """
        SystemBackup application class constructor

        @param self (object) object reference
        @param args (Argparse.Namespace) application arguments

        @returns None
        """
        app_config = args.app_config
        host_config = args.host_config

        self.app_config  = self._load_application_config(app_config)
        self.host_config = self._load_host_config(host_config)

        pass

    def main(self, host):
        """
        Application Entry point

        @param self (object) object reference
        @param host (string) identifier of the host to run

        @returns None
        """
        pass

    def _rsync_host_test(self):
        """
        Test to ensure that the host does have the rsync binary available

        @param self (object) object reference

        @returns (boolean) True if it exists, false otherwise
        """
        pass
