#!/usr/bin/env python3

"""
Copyright 2017 Pirate Hour Productions

Author: Alan Drees

Purpose: Application class implementation for the system-backup command

"""

import sys
import argparse
import yaml
import subprocess

class SystemBackup:

